"""initial

Revision ID: e48213589127
Revises: 
Create Date: 2023-04-20 19:54:42.912917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48213589127'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacja', sa.String(length=50), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=True),
    sa.Column('sztuk', sa.Integer(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('przedmiot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('sztuk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo')
    op.drop_table('przedmiot')
    op.drop_table('historia')
    # ### end Alembic commands ###
